### ISSUE TITLE
com.google.inject.ConfigurationException: Guice configuration errors:  Could not find a suitable constructor in org.reactivecouchbase.play.plugins.CouchbasePlugin

### ISSUE THREAD

**Issue by pcboy** [ReactiveCouchbase/ReactiveCouchbase-play#42]
For an unknown reason I can't run my UT and IT tests anymore.  
Something is broken between ReactiveCouchbase-play and guice it seems. But I have a hard time to find where.  
The really strange thing is that it's working in dev and prod modes. Only the tests are giving me that error.  
Any clues?

I have:  
"com.typesafe.play" % "sbt-plugin" % "2.3.+" and  
 "org.reactivecouchbase" %% "reactivecouchbase-play" % "0.4-SNAPSHOT",
in my dependencies.

Thanks,

```
[info] ApplicationSpecIT:
[info] Exception encountered when attempting to run a suite with class name: it.ApplicationSpecIT *** ABORTED *** (1 second, 217 milliseconds)
[info]   com.google.inject.ConfigurationException: Guice configuration errors:
[info] 
[info] 1) Could not find a suitable constructor in org.reactivecouchbase.play.plugins.CouchbasePlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
[info]   at org.reactivecouchbase.play.plugins.CouchbasePlugin.class(CouchbasePlugin.scala:12)
[info]   while locating org.reactivecouchbase.play.plugins.CouchbasePlugin
[info] 
[info] 1 error
[info]   at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
[info]   at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
[info]   at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
[info]   at play.api.inject.guice.GuiceInjector.instanceOf(GuiceApplicationLoader.scala:140)
[info]   at play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:89)
[info]   at play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:87)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[info]   at scala.collection.immutable.List.map(List.scala:284)
[info]   at play.api.Plugins$.loadPlugins(Plugins.scala:87)
[info]   at play.api.test.FakeApplication.<init>(Fakes.scala:253)
[info]   at org.scalatestplus.play.OneServerPerSuite$class.app(OneServerPerSuite.scala:151)
[info]   at it.ApplicationSpecIT.app$lzycompute(ApplicationSpecIT.scala:14)
[info]   at it.ApplicationSpecIT.app(ApplicationSpecIT.scala:14)
[info]   at org.scalatestplus.play.OneServerPerSuite$class.run(OneServerPerSuite.scala:172)
[info]   at it.ApplicationSpecIT.run(ApplicationSpecIT.scala:14)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:462)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:671)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:235)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 2 seconds, 271 milliseconds.
```

**Comment by pcboy** [comment]
Found the solution after many hours of pain.

I had this in my build.sbt:  

  "org.scalatestplus" %% "play" % "1.+" % "it,test",

The thing is the versioning of scalatestplus is kinda fuckedup.  

http://scalatest.org/plus/play/versions

I'm on Play 2.3 but scalatestplus 1.3.0 only works on Play 2.2.
So I had to switch to 1.**2**.0 to fix the issue... Now my tests are passing.
